class ProjectConst {
  static const NORMAL_TEXTFORMFIELD_MAX_LENGTH = 40;
  static const EMAIL_TEXTFORMFIELD_MAX_LENGTH = 100;
  static const PLACEHOLDER = '##';
  static const PHONE_NUMBER_TEXTFORMFIELD_MAX_LENGTH = 15;
  static const FISCAL_CODE_TEXTFORMFIELD_MAX_LENGTH = 16;
}
